name: Feature
description: A small, atomic feature with clear acceptance criteria.
title: "[Feature] "
labels: ["feature"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Link to docs/MVP.md and any relevant notes.
      value: "See docs/MVP.md"
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: Task
      description: Describe one feature only.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Binary, testable criteria.
      placeholder: "- Given ..., when ..., then ..."
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Minimal diff, no refactors, follow existing patterns.
      value: |
        - Minimal diff
        - No refactors unless requested
        - Follow existing patterns
    validations:
      required: true

  - type: textarea
    id: testplan
    attributes:
      label: Test plan
      description: Exact steps or commands that must pass.
      placeholder: "- Open Scene X, press Play, do Y, observe Z"
    validations:
      required: true
